### ISSUE TITLE
Missing File when converting STL to Voxels

### ISSUE THREAD

**Issue by Connelly-code** [cdbrauer/VoxelFuse#28]
The fromMeshfile function appears to not properly create a file called output.msh which is called when referring to the data = meshio.read function.  Could be an issue with meshio or voxelfuse.  Problem will occur when running the example code for voxelfuse 'voxelfuse_examples.load_mesh.load_mesh' file.

**Comment by jnbrauer** [comment]
Fixed by 46a94968bf1f5eaf2052aa7fce82376af0f3b61f. Issue was caused by a bug in how filepaths with spaces were handled.
